apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: helloworld
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
  type: NodePort
